Related Work
===========
:Author:    Markus Reinhold


(1) flutter native module import native android ios 2023-02-12


=== https://www.diva-portal.org/smash/get/diva2:1442804/FULLTEXT01.pdf[A Comparison of Performance and Looks Between Flutter and Native Applications] (1)


==== Research Questions

RQ1: How does Flutter differentiate in code size and how complex code is needed in comparison to native built applications?

RQ2: How well does Flutter perform in run time CPU usage compared to native applications on Android and iOS?

RQ3: How much does Flutter and android native differentiate in terms of look and feel for the application users?

-> Flutter native apps compiled und keine Module verwendet

-> hier werden Performance Tests manuell durchgeführt

-> Interessante Umfrage, ob Flutter / native dem Endnutzer auffällt


=== https://blog.codemagic.io/flutter-vs-android-ios-xamarin-reactnative/[Flutter Versus Other Mobile Development Frameworks: A UI And Performance Experiment. Part 2]

Hier stellt sich heraus, dass die getestete Flutter App performanter als bspw. eine native App ist, Tests erfolgten manuell (ein mal?), über Android Profiler, nur CPU-Usage